#!/bin/bash
#
# Restart production / stagging cluster
#
# @author anthonycorbacho
#

IFS=$','

#export ANSIBLE_ERROR_ON_UNDEFINED_VARS=True
export ANSIBLE_HOST_KEY_CHECKING=False

if [[ $# -gt 0 ]]; then
  echo 'Running ansible-playbook -i hosts restart.yml --tags' "$*"
  ansible-playbook --user=root --ask-pass -i hosts restart.yml --tags "$*"
else
  echo 'Running ansible-playbook -i hosts restart.yml'
  ansible-playbook --user=root --ask-pass -i hosts restart.yml
fi
